[general]
import = [
  "~/.cache/wal/colors-alacritty.toml",
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
padding = { x = 15, y = 15 }
decorations = "None"
opacity = 0.9

[font]
normal = { family = "codespace", style = "Regular" }
size = 12.0

[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = { shape = "Beam", blinking = "On" }
