#!/bin/sh

depends native git

if is arch platform; then
    depends native git-delta
else
    depends cargo git-delta
fi

pre_install() {
     # Make sure template directory exists
     if ! is "$HOME/Templates" directory; then
         mkdir -p "$HOME/Templates"
     fi
}
