[backdrop]
enabled = true
blur-intensity = 0.75
tint-intensity = 0.5

[control_center]
sidebar = "full"

[location]
auto_locate = true

[lockscreen]
blurred_desktop = true
blur_intensity = 0.9
tint_intensity = 0.5

[shell]
niri_overview_type_to_launch_enabled = true

[shell.panel]
transparency_mode = "glass"

[theme]
source = "wallpaper"

[theme.templates]
builtin_ids = [ "gtk3", "gtk4", "kcolorscheme", "niri", "qt" ]
community_ids = [ "spicetify", "zen-browser", "discord", "papirus-icons" ]

[theme.templates.user.emacs]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/emacs.el"
output_path = "$XDG_CONFIG_HOME/emacs/etc/themes/noctalia-theme.el"
post_hook = "emacsclient -e \"(load-theme 'noctalia t)\""

[wallpaper]
directory = "~/Pictures/Wallpapers"
per_monitor_directories = true
automation.enabled = true