# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username $hostname $directory $git_branch\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$crystal\
$cmd_duration
$character\
$status
"""
add_newline = true

[username]
format = '[$user]($style)'
show_always = true

[hostname]
format = 'at [$ssh_symbol$hostname]($style)'
ssh_only = false

[directory]
format = 'in [$path]($style)[$read_only]($read_only_style)'

[package]
format = 'with [$symbol$version]($style) '

[character]
success_symbol = '[\(✿ •⌄•\)](green)'
error_symbol = '[\(✿ ›_‹\)](red)'

[status]
disabled = false
format = '[$common_meaning$symbol]($style) '
style = 'bold red'
map_symbol = true
success_symbol = '[ ](bold green)'
symbol = '  '
not_executable_symbol = '  '
not_found_symbol = '  '
sigint_symbol = '  '
signal_symbol = '  '

[cmd_duration]
format = 'after [$duration]($style)'
