#!/bin/sh

depends native pulseaudio \
               bspwm \
               sxhkd \
               dunst \
               feh \
               wmname \
               picom

is arch platform && depends aur polybar

depends dotfile gtk wal uim fontconfig

pre_install() {
    # Make sure these directories exist
    if ! is "$HOME/Pictures/Resources" directory; then
        mkdir -p ~/Pictures/Resources
    fi

    mkdir -p ~/.config/systemd/user

    mkdir -p ~/.local/bin
}
