#!/bin/sh

depends native pulseaudio \
               bspwm \
               sxhkd \
               dunst \
               feh \
               wmname \
               picom

is platform arch?
if yes; then depends aur polybar; fi

depends dotfile gtk wal uim fontconfig

pre_install() {
    # Make sure these directories exist
    is "~/Pictures/Resources" directory?
    if no; then
        mkdir -p ~/Pictures/Resources
    fi

    is "~/.config/systemd/user" directory?
    if no; then
        mkdir -p ~/.config/systemd/user
    fi

    is "~/.local/bin" directory?
    if no; then
        mkdir -p ~/.local/bin
    fi
}
