#+title: Emacs configuration

This document describes and configures my Emacs instance.

While most of the configurations are available in this document, there are couple essential settings in the =early-init.el= file.
Most of them are load- and performance-related options.

* Emacs Initialization
Before loading any other configuration, there are some things that need to be taken care of.
Put those "prerequisite routines" here.

** Garbage Collection
Emacs has a tiny GC threshold.
It may have been useful some 15 years ago, but it is fair to increase the size for modern computers.

Before running this script, the ~early-init.el~ file should have the threshold increased to its maximum.
Since initialization process requires a lot of computation, we will keep that threshold, and change it once initialization is over.

Also, using the minibuffer will cause the GC threshold to increase, and Emacs will try to collect garbages when focus is lost.

#+begin_src emacs-lisp
  (defconst rangho--gc-cons-threshold
    (* 64 1024 1024)
    "The default value of `gc-cons-threshold'.")

  (defconst rangho--gc-cons-percentage
    0.4
    "The default value of `gc-cons-percentage'.")

  (defun rangho--set-excessive-gc ()
    "Set the garbage collector threshold for high-speed usage."
    (setq gc-cons-threshold most-positive-fixnum
          gc-cons-percentage 0.6))

  (defun rangho--set-reasonable-gc ()
    "Set the garbage collector threshold for normal usage."
    (setq gc-cons-threshold rangho--gc-cons-threshold
          gc-cons-percentage rangho--gc-cons-percentage))

  (defun rangho--collect-garbage-on-focus-change ()
    "Collect garbage when Emacs noticese a focus change event."
    (unless (frame-focus-state)
      (garbage-collect)))

  (add-hook 'after-init-hook #'rangho--set-reasonable-gc)

  (add-hook 'minibuffer-setup-hook #'rangho--set-excessive-gc)
  (add-hook 'minibuffer-exit-hook #'rangho--set-reasonable-gc)

  (add-function :after after-focus-change-function
                #'rangho--collect-garbage-on-focus-change)
#+end_src

** Package Manager
Emacs has a pretty decent package manager built-in.

#+begin_src emacs-lisp
  (require 'package)
#+end_src

The vanilla configuration lacks many plugins that don't meed GNU standards, though.
Let's add [[https://melpa.org][MELPA]] to rectify that.

#+begin_src emacs-lisp
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
#+end_src

If there is a newer version of built-in packages available, upgrade them.

#+begin_src emacs-lisp
  (setq package-install-upgrade-built-in t)
#+end_src

We're going to use ~use-package~ to wrap the package management functionality.

#+begin_src emacs-lisp
  (require 'use-package)
  (require 'use-package-ensure)
#+end_src

There are following switches available:

- ~use-package-always-ensure~ :: Make sure that packages get installed if not present in system.
- ~use-package-always-defer~ :: Defer the actual loading of the package until it is actually needed.
- ~use-package-always-demand~ :: Force the package to load immediately when specified.
- ~use-package-always-pin~ :: Pin every package to the specified package archive.

#+begin_src emacs-lisp
  (setq use-package-always-ensure t)
#+end_src

If I need to load a package right away, simply specify ~:demand t~ to override the deferral setting.

* Constants and Environments
These are some constants that are used throughout the configuration.
Also, let's set up some environmental settings.

** Name and Email
My name and email address.

#+begin_src emacs-lisp
  (defconst user-full-name
    "RangHo Lee"
    "My full name.")

  (defconst user-mail-address
    "hello@rangho.me"
    "My email address.")
#+end_src

** XDG Base Directories
These constants resolve to user directories akin to the XDG Base Directory specifications, independent of the platform.

#+begin_src emacs-lisp
  (defconst user-home-directory
    (cond ((eq system-type 'windows-nt)
           (file-name-as-directory (getenv "UserProfile")))
          ((getenv "HOME")
           (file-name-as-directory (getenv "HOME")))
          (t (file-name-as-directory "~")))
    "Per-user home directory.")

  (defconst user-config-directory
    (cond ((eq system-type 'windows-nt)
           (file-name-as-directory (getenv "AppData")))
          ((getenv "XDG_CONFIG_HOME")
           (file-name-as-directory (getenv "XDG_CONFIG_HOME")))
          (t
           (file-name-as-directory
            (expand-file-name ".config" user-home-directory))))
    "Per-user configuration directory.")

  (defconst user-data-directory
    (cond ((eq system-type 'windows-nt)
           (file-name-as-directory (getenv "AppData")))
          ((getenv "XDG_DATA_HOME")
           (file-name-as-directory (getenv "XDG_DATA_HOME")))
          (t
           (file-name-as-directory
            (expand-file-name ".local/share" user-home-directory))))
    "Per-user data directory.")

  (defconst user-cache-directory
    (cond ((eq system-type 'windows-nt)
           (file-name-as-directory (concat user-data-directory "Cache")))
          ((getenv "XDG_CACHE_HOME")
           (file-name-as-directory (getenv "XDG_CACHE_HOME")))
          (t
           (file-name-as-directory
            (expand-file-name ".cache" user-home-directory))))
    "Per-user cache directory.")
#+end_src

** Default Shell
I use different shells on different systems, and Emacs seems to work the best when combined with POSIX-compliant shells.
Let's fix the shell to ~/bin/sh~ if on a supported platform.

#+begin_src emacs-lisp
  (unless (eq system-type 'windows-nt)
    (setq shell-file-name "/bin/sh"))
#+end_src

** Input Method
Emacs comes with various input methods.
It seems Wayland + Niri + IBus combo doesn't work well with GTK Emacs.
Let's just use built-in input method here.

#+begin_src emacs-lisp
  (setq default-input-method "korean-hangul390")
  (when (string= (getenv "XDG_SESSION_TYPE") "wayland")
    (global-set-key (kbd "<Hangul>") 'toggle-input-method))
#+end_src

** Override Built-in Packages
There are some packages that need periodic upgrades from ELPA.
Make sure that we are using the correct version every time.

*** ~compat~
~compat~ ensures backwards and forwards compatibility with other Emacs versions.
Usually, the built-in version lags behind by quite a lot, so let's just have it use the version from ELPA.

#+begin_src emacs-lisp
  (use-package compat
    :pin gnu
    :init
    (unload-feature 'compat t))
#+end_src

** Mise Version Manager
[[https://mise.jdx.dev/][Mise]] is a "unified" version manager that can install multiple versions of various utilities and compilers.
If a binary called =mise= is available, load the 3rd-party Emacs integration package.

#+begin_src emacs-lisp
  (use-package mise
    :when (executable-find "mise")
    :hook (after-init . global-mise-mode))
#+end_src

* Built-in Settings
This section contains modifications of built-in functionalities of Emacs.

** Parameter Adjustments
Some things in Emacs are controlled by their customization variables.
Since I will not use ~use-package~ for those vanilla Emacs variables, put them all here for organization.

Order it by importance, or rather, how annoying it is if not set up correctly.

*** Startup Items
Disable some startup routines to make Emacs cleaner.

#+begin_src emacs-lisp
  (setq inhibit-startup-screen t)
  (setq inhibit-startup-message t)
  (setq inhibit-startup-echo-area-message t)
#+end_src

*** Suppress Warnings
Let me know when things go /seriously/ wrong.

#+begin_src emacs-lisp
  (setq warning-minimum-level :error)
#+end_src

*** Word-wrapping for Text
When writing text, I tend to put a single sentence in a single line.
But, when the line gets too long, they overflow to the right, making things harder to read.
~visual-line-mode~ can address this problem.

#+begin_src emacs-lisp
  (add-hook 'text-mode-hook #'visual-line-mode)
#+end_src

*** Frame Styles
Some UI elements are controlled with per-frame association lists.

#+begin_src emacs-lisp
  (setq default-frame-alist
        `((undecorated . t)
          (width . 115) ; 80 col of editor + 35 col of treemacs
          (height . 25)
          (vertical-scroll-bars . nil)
          (horizontal-scroll-bars . nil)
          (right-divider-width . 3)
          (internal-border-width . 20)))
#+end_src

*** No Tabs
Fuck tabs, they're different on every platform.

#+begin_src emacs-lisp
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 4)
  (setq-default tab-stop-list (number-sequence 4 120 4))
#+end_src

** Minor Modes
Minor modes in Emacs are "optional editing mode that alters the behavior of Emacs in some well-defined way".
There are a lot of built-in minor modes, including those responsible for some UI elements.
This section handles and customizes those.

*** Mouse Support
There are a bit of things to tweak when using mouse.

If Emacs is running in a CLI mode, we can enable mouse support for Xterm.

#+begin_src emacs-lisp
  (unless (display-graphic-p)
    (xterm-mouse-mode +1))
#+end_src

The default scroll movement is pretty aggressive, so we need to tone it down a bit.

#+begin_src emacs-lisp
  (setq mouse-wheel-scroll-amount '(3 ((control) . 1) ((shift) . 5)))
  (setq mouse-wheel-progressive-speed nil)
#+end_src

*** History of Buffers and Commands
Make sure Emacs keeps the history of visited files and executed commands.

#+begin_src emacs-lisp
  (savehist-mode +1)
  (recentf-mode +1)
#+end_src

*** Revert Files Automatically
If files are changed in the background, reflect the latest changes.

#+begin_src emacs-lisp
  (setq auto-revert-interval 1)
  (global-auto-revert-mode +1)
#+end_src

*** Electric Modes
Emacs comes with a few "electric" modes that intervenes and edits text on-the-fly:

- ~electric-pair-mode~ :: Insert corresponding closing pair when typing "opening" characters.
- ~electric-indent-mode~ :: Re-indent the line when a possible indent-requiring events fire.

#+begin_src emacs-lisp
  (electric-indent-mode +1)
  (electric-pair-mode +1)
#+end_src

*** Syntax Checking
There is a syntax version of the spell checker called ~flymake~.
They collect diagnostic information from multiple sources and display them in a user-friendly way.

#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook #'flymake-mode)
#+end_src

*** Spell Checking
Emacs has built-in integration with =ispell=-like spell checkers.

Also, ~flyspell~ enables /on-the-fly/ spell checking, just like other word processors do.
There are two sub-modes available for this package:

- ~flyspell-mode~ :: Check spelling for all text in the buffer.
- ~flyspell-prog-mode~ :: Check spelling, only within comments and strings.
  
#+begin_src emacs-lisp
  (when-let* ((hunspell-program (executable-find "hunspell")))
    (setq ispell-program-name hunspell-program)
    (add-hook 'text-mode-hook #'flyspell-mode))
#+end_src

*** Documentations
Let's enable Eldoc mode for all buffers.

#+begin_src emacs-lisp
  (global-eldoc-mode +1)
#+end_src

*** UI Elements
Some UI elements are exposed as minor modes, and I'm not happy with the default.

#+begin_src emacs-lisp
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (tooltip-mode -1)

  (global-hl-line-mode +1)
  (show-paren-mode +1)
#+end_src

** Modern Editing Features
Some editing features have been modularized these days, and Emacs has built-in integrations for many of them.

*** Tree-sitter Integration
Starting from Emacs 29, the [[https://tree-sitter.github.io/tree-sitter/][Tree-sitter]] support is built-in.
It is usually much faster than Emacs's built-in parsing facility.

#+begin_src emacs-lisp
  (require 'treesit)

  (defvar treesit-major-mode-remap-alist
    nil
    "Association list of major modes to remap to their respective tree-sitter alternatives.")

  (defun treesit-install-all-language-grammars (&optional out-dir)
    "Build and install all tree-sitter language grammar libraries.

  It builds all available grammars specified in `treesit-language-source-alist'.
  Interactively, it prompts for the directory in which to install the compiled
  grammar files.  Non-interactively, use OUT-DIR; if it is nil, the grammars are
  installed to the standard location, the \"tree-sitter\" directory under
  `user-emacs-directory'."
    (interactive (list (read-directory-name
                        "Install to: "
                        (or (car treesit--install-language-grammar-out-dir-history)
                            (locate-user-emacs-file "tree-sitter")))))
    (mapcar (lambda (grammar)
              (treesit-install-language-grammar
               (car grammar)
               (or out-dir
                   (car treesit--install-language-grammar-out-dir-history
                        (locate-user-emacs-file "tree-sitter")))))
            treesit-language-source-alist))
#+end_src

*** Language Server Protocol
The [[https://microsoft.github.io/language-server-protocol/][Language Server Protocol]] allows editor-agonistic programming support by implementing server-client relationship.

#+begin_src emacs-lisp
  (require 'eglot)

  (defun rangho--ensure-eglot-if-supported (&optional mode)
    "Enable eglot if it is supported for MODE or the current major mode."
    (let ((mode (or mode major-mode)))
      (when (eglot--lookup-mode mode)
        (eglot-ensure))))

  (add-hook 'prog-mode-hook #'rangho--ensure-eglot-if-supported)
#+end_src

* External Packages
This section contains anything that is not included in vanilla Emacs.

** Enhancements
*** Rainbow Delimiters
Colorful parentheses help distinguish which opens and closes which.
Basically, a must-have for Lisp.

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook (prog-mode))
#+end_src

*** Preview Color Codes
~rainbow-mode~ changes the background of color representations in a source code.
This is especially useful for stylesheets, etc.

#+begin_src emacs-lisp
  (use-package rainbow-mode
    :hook (prog-mode)
    :custom
    (rainbow-r-colors nil)
    (rainbow-x-colors nil))
#+end_src

*** In-buffer Completions
In-buffer completion engines complete texts in buffers, similar to Visual Studio IntelliSense.
~corfu~ utilizes the built in ~completion-at-point~ functionalities to provide such completions.

~corfu~, short for COmpletion in Region FUnction, aims to provide nice UI using child frames.

#+begin_src emacs-lisp
  (defun rangho--enable-corfu-in-minibuffer ()
    "Enable `corfu-mode' in the minibuffer, if supported."
    (when (local-variable-p 'completion-at-point-functions)
      (setq-local corfu-auto nil
                  corfu-echo-display nil
                  corfu-popupinfo-delay nil)
      (corfu-mode +1)))

  (use-package corfu
    :hook (minibuffer-setup . rangho--enable-corfu-in-minibuffer)
    :custom
    (corfu-auto t)
    (corfu-cycle t)
    (corfu-popupinfo-delay '(1 . 1))
    :config
    (global-corfu-mode +1)
    (corfu-popupinfo-mode +1))
#+end_src

While it /can/ utilize the built-in completion functions, ~cape~ can provide far more "backends".

#+begin_src emacs-lisp
  (use-package cape
    :bind (("C-c p p" . completion-at-point)
           ("C-c p t" . complete-tag)
           ("C-c p d" . cape-dabbrev)
           ("C-c p h" . cape-history)
           ("C-c p f" . cape-file)
           ("C-c p k" . cape-keyword)
           ("C-c p s" . cape-elisp-symbol)
           ("C-c p e" . cape-elisp-block)
           ("C-c p a" . cape-abbrev)
           ("C-c p l" . cape-line)
           ("C-c p w" . cape-dict)
           ("C-c p :" . cape-emoji)
           ("C-c p \\" . cape-tex)
           ("C-c p _" . cape-tex)
           ("C-c p ^" . cape-tex)
           ("C-c p &" . cape-sgml)
           ("C-c p r" . cape-rfc1345))
    :init
    (add-hook 'completion-at-point-functions #'cape-dabbrev)
    (add-hook 'completion-at-point-functions #'cape-file))
#+end_src

*** Minibuffer Completions
Minibuffer completions complete anything displayed in the minibuffer.

~vertico~ is `a nice solution for minibuffer completions.

#+begin_src emacs-lisp
  (use-package vertico
    :config
    (vertico-mode +1))
#+end_src

~marginalia~ displays annotations about each interactive commands in =M-x= windows.

#+begin_src emacs-lisp
  (use-package marginalia
    :config
    (marginalia-mode +1))
#+end_src

~orderless~ provides a powerful completion style where I can match with space-separated keywords without order.

#+begin_src emacs-lisp
  (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

*** View Incomplete Keybindings
Sometimes, typing =C-h k= is too much.
Let's just throw shit at the wall and see what sticks.

#+begin_src emacs-lisp
  (use-package which-key
    :config
    (which-key-mode +1))
#+end_src

*** Documentations in a Box
There is a package that shows ~eldoc~ contents within a child frame.

#+begin_src emacs-lisp
  (use-package eldoc-box
    :hook (prog-mode . eldoc-box-hover-at-point-mode)
    :custom
    (eldoc-echo-area-prefer-doc-buffer t))
#+end_src

*** Evil Mode
For text editing and navigation, ~evil~ is still much better than "The Emacs Way".

#+begin_src emacs-lisp
  (use-package evil
    :custom
    (evil-undo-system 'undo-redo)
    (evil-split-window-below t)
    (evil-vsplit-window-right t)
    (evil-want-integration t "Requirement for `evil-collection'.")
    (evil-want-keybinding nil "Requirement for `evil-collection'.")
    :config
    (evil-mode +1))

  (use-package evil-collection
    :config
    (evil-collection-init))

  (use-package evil-surround
    :config
    (global-evil-surround-mode +1))
#+end_src

~treemacs~ has ~evil~ integration.

#+begin_src emacs-lisp
  (use-package treemacs-evil
    :after (treemacs))
#+end_src

*** God Mode
God-mode prevents the "Emacs Pinky" by allowing us to chain keybindings with plain letters.

#+begin_src emacs-lisp
  (use-package god-mode)
#+end_src

*** Limiting Text Mode to Fill Column
There is a small package called ~visual-fill-column~ that extends the built-in ~visual-line-mode~ so that it acknowledges ~fill-column~.

#+begin_src emacs-lisp
  (use-package visual-fill-column
    :hook (markdown-mode org-mode)
    :custom
    (visual-fill-column-center-text t)
    (visual-fill-column-width 120))
#+end_src

*** Vertically Aligned Tables
Many markup languages (including Markdown and Org-mode) draws tables in a form of ASCII art.
These look nice when everything is made of monospace texts, but as soon as we put proportional fonts into play, they become a nightmare.

#+begin_src emacs-lisp
  (use-package valign
    :hook (markdown-mode org-mode)
    :custom
    (valign-fancy-bar t))
#+end_src

*** Ligature
Ligature provide alternative combined glyphs for commonly used character combinations (such as operators).

#+begin_src emacs-lisp
  (defconst rangho--prog-mode-ligatures
    '("--" "---" "==" "===" "!=" "!==" "=!="
      "=:=" "=/=" "<=" ">=" "&&" "&&&" "&=" "++" "+++" "***" ";;" "!!"
      "??" "???" "?:" "?." "?=" "<:" ":<" ":>" ">:" "<:<" "<>" "<<<" ">>>"
      "<<" ">>" "||" "-|" "_|_" "|-" "||-" "|=" "||=" "##" "###" "####"
      "#{" "#[" "]#" "#(" "#?" "#_" "#_(" "#:" "#!" "#=" "^=" "<$>" "<$"
      "$>" "<+>" "<+" "+>" "<*>" "<*" "*>" "</" "</>" "/>" "<!--" "<#--"
      "-->" "->" "->>" "<<-" "<-" "<=<" "=<<" "<<=" "<==" "<=>" "<==>"
      "==>" "=>" "=>>" ">=>" ">>=" ">>-" ">-" "-<" "-<<" ">->" "<-<" "<-|"
      "<=|" "|=>" "|->" "<->" "<~~" "<~" "<~>" "~~" "~~>" "~>" "~-" "-~"
      "~@" "[||]" "|]" "[|" "|}" "{|" "[<" ">]" "|>" "<|" "||>" "<||"
      "|||>" "<|||" "<|>" "..." ".." ".=" "..<" ".?" "::" ":::" ":=" "::="
      ":?" ":?>" "//" "///" "/*" "*/" "/=" "//=" "/==" "@_" "__" "???"
      "<:<" ";;;")
    "List of ligatures to enable in `prog-mode' buffers.")

  (use-package ligature
    :config
    (ligature-set-ligatures 'prog-mode rangho--prog-mode-ligatures)
    (global-ligature-mode +1))
#+end_src

*** Nerd Fonts
[[https://www.nerdfonts.com/][Nerd Fonts]] can be used to show icons in Emacs environment.
This requires a font called "Symbols Nerd Font Mono" being present on the system.

#+begin_src emacs-lisp
  (use-package nerd-icons
    :custom
    (nerd-icons-font-family "Symbols Nerd Font Mono"))
#+end_src

~dired~, the Emacs directory editor, can be prettified with Nerd Fonts.

#+begin_src emacs-lisp
  (use-package nerd-icons-dired
    :hook (dired-mode))
#+end_src

~corfu~ can show VSCode-like icons for different completion items.

#+begin_src emacs-lisp
  (use-package nerd-icons-corfu
    :after corfu
    :config
    (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
#+end_src

~treemacs~ can show Nerd Fonts icons instead of its default icon pack.

#+begin_src emacs-lisp
  (use-package treemacs-nerd-icons
    :config
    (treemacs-load-theme "nerd-icons"))
#+end_src

** Utilities

*** Fancy Startup Dashboard
By default, Emacs shows the =*scratch*= buffer if startup screen is inhibited.
There is a fancier version of dashboard.

#+begin_src emacs-lisp
  (use-package dashboard
    :hook ((after-init . dashboard-insert-startupify-lists)
           (after-init . dashboard-initialize)
           (window-setup . dashboard-resize-on-hook))
    :custom
    (dashboard-display-icons-p t)
    (dashboard-set-file-icons t)
    (dashboard-set-heading-icons t)
    (dashboard-startup-banner (expand-file-name "usr/share/gnu-emacs.png" user-emacs-directory))
    (dashboard-image-banner-max-height 400)
    (dashboard-icon-type 'nerd-icons)
    :init
    (add-to-list 'window-size-change-functions #'dashboard-resize-on-hook)
    :config
    (setq initial-buffer-choice (lambda ()
                                  (dashboard-insert-startupify-lists t)
                                  (get-buffer-create dashboard-buffer-name))))
#+end_src

*** Nyan Cat Scrollbar!
Nyanyanyanyanyanyanya!

#+begin_src emacs-lisp
  (use-package nyan-mode
    :custom
    (nyan-bar-length 22)
    (nyan-minimum-window-width 100)
    (nyan-animate-nyancat t)
    (nyan-wavy-trail t))
#+end_src

*** Navigation
~treemacs~ is to Emacs as =NerdTree= is to (Neo)Vim.
It's really good.

#+begin_src emacs-lisp
  (use-package treemacs
    :config
    (treemacs-follow-mode +1)
    (treemacs-filewatch-mode +1)
    (pcase (cons (not (null (executable-find "git")))
                 (not (null treemacs-python-executable)))
      (`(t . t)
       (treemacs-git-mode 'deferred)
       (treemacs-git-commit-diff-mode +1))
      (`(t . _)
       (treemacs-git-mode 'simple))))
#+end_src

*** Snippets
Snippets make life so much easier by creating repetitive boilerplate codes for me.

#+begin_src emacs-lisp
  (use-package yasnippet
    :config
    (yas-global-mode +1))

  (use-package yasnippet-snippets)
#+end_src

*** Debug Adapter Protocol
The [[https://microsoft.github.io/debug-adapter-protocol/][Debug Adapter Protocol]] is similar to the [[https://sourceware.org/gdb/current/onlinedocs/gdb.html/GDB_002fMI.html#GDB_002fMI][GDB/MI]] interface as it provides a server-client relationship between the debugger and the UI.

#+begin_src emacs-lisp
  (use-package dape)
#+end_src

*** Terminal Emulator
Emacs has an ANSI terminal emulator, but it is rather slow.
~eat~ is a fast terminal emulator implemented in Emacs Lisp, and supports much more features such as sixels and mouse navigation.
It doesn't work on WIndows, though.

#+begin_src emacs-lisp
  (use-package eat
    :unless (eq system-type 'windows-nt)
    :bind (("C-c RET" . eat))
    :hook ((eshell-load . eat-eshell-mode)
           (eshell-load . eat-eshell-visual-command-mode)))
#+end_src

*** Embedding Font Lock Faces

#+begin_src emacs-lisp
  (use-package engrave-faces)
#+end_src

** Integrations

*** Git Integration
~magit~ is the greatest Git client.

#+begin_src emacs-lisp
  (defun rangho--set-fill-column-to-72 ()
    "Set `fill-column' to 72 for git commit messages."
    (setq fill-column 72))

  (use-package magit
    :hook (git-commit-setup . rangho--set-fill-column-to-72))
#+end_src

~treemacs~ has ~magit~ integration.

#+begin_src emacs-lisp
  (use-package treemacs-magit)
#+end_src

*** EditorConfig Integration
[[https://editorconfig.org/][EditorConfig]] is a pretty widely-supported method of ensuring consistent code style across many developers.

#+begin_src emacs-lisp
  (use-package editorconfig
    :config
    (editorconfig-mode +1))
#+end_src

*** Discord Integration
Discord has a feature called *Rich Presence* where a process can send an update to the Discord socket to display things under the user profile.
Emacs has an unofficial plugin for that, to show off what I'm doing.

#+begin_src emacs-lisp
  (use-package elcord
    :custom
    (elcord-use-major-mode-as-main-icon t)
    (elcord-quiet t))
#+end_src

*** GitHub Copilot Integration
I now outsource thinking to [[https://github.com/features/copilot][GitHub Copilot]] now.

#+begin_src emacs-lisp
  (use-package copilot
    :bind (("C-SPC" . copilot-complete)
           :map copilot-completion-map
           ("C-g" . 'copilot-clear-overlay)
           ("M-p" . 'copilot-previous-completion)
           ("M-n" . 'copilot-next-completion)
           ("TAB" . 'copilot-accept-completion)
           ("M-TAB" . 'copilot-accept-completion-by-word)
           ("M-RET" . 'copilot-accept-completion-by-line)))
#+end_src

*** AI Agent Integration
I can even outsource typing to AI agents too.

#+begin_src emacs-lisp
  (use-package eca)
#+end_src

* Local Packages
There are some packages I developed but couldn't care less to package it properly.

** "Hades" Mode
When God is Evil, He becomes Hades.
~hades-mode~ integrates ~evil-mode~ and ~god-mode~ into a single package.

You can enter ~god-mode~ state by pressing =,= in the NORMAL state.

#+begin_src emacs-lisp
  (use-package hades
    :ensure nil
    :after (evil god-mode)
    :config
    (evil-define-key 'normal global-map "," #'hades-start-execute-in-hades-state)
    (evil-define-key 'hades global-map (kbd "<escape>") #'hades-cancel))
#+end_src

** Line Numbers
Display line numbers for computer codes.
For regular texts, usually they are more of an annoyance.

#+begin_src emacs-lisp
  (use-package evil-line-numbers
    :ensure nil
    :after (evil)
    :hook (prog-mode)
    :custom
    (display-line-numbers-width 3))
#+end_src

** Mixed-pitch Support
Emacs can display text in a /mixed-pitch/ manner, where both variable-pitch and fixed-pitch fonts can exist in a single buffer.
I wrote a small utility called ~mixed-pitch-mode~ that utilizes ~face-remap~ facility.
(There exists a package with the same name that does the same thing, but without proper fontset support, CJK characters are not displayed correctly.)

#+begin_src emacs-lisp
  (use-package mixed-pitch
    :ensure nil
    :hook (markdown-mode org-mode))
#+end_src

** Fonts
Fonts are super important, not because they're pretty, but because it greatly affects the readability of a text.
Here is a set of fonts I use.

#+begin_notes
On Linux, dual-width CJK fonts are not aligned correctly if the font height does not match with its intended DPI settings.
For =hesalche=, the correct height is 120 while for =semteulche=, it is 110.

On Windows, dual-width fonts are not rendered well as all characters are rendered as if they were full-width.
For now, do not install =hesalche= and =semteulche= on Windows until I find a way to detect dual-width fonts.
#+end_notes

#+begin_src emacs-lisp
  ;; Sample sentences to check font support:
  ;;   - Latin:  The quick brown fox jumps over the lazy dog.
  ;;   - Hangul: 다람쥐 헌 쳇바퀴에 타고파.
  ;;   - Kana:   いろはにほへと ちりぬるを / わかよたれそ つねならむ
  ;;   - Emoji:  I'm blue, da💨 ba🐋 dee👖 da📘 ba💙 dai🌊

  (use-package rangho-fonts
    :ensure nil
    :custom
    (rangho-fonts-fixed-font-alist
     '((nil "hesalche" "semteulche"
            "Noto Sans Mono"
            "Cascadia Code" "Consolas" "Courier New"
            "monospace")
       (hangul "hesalche" "semteulche"
               "Noto Sans Mono CJK KR"
               "DotumChe" "GulimChe"
               "monospace")
       (kana "Noto Sans Mono CJK JP"
             "GulimChe" "DotumChe"
             "monospace")
       (han ("Noto Sans Mono CJK SC" "Noto Sans Mono CJK TC")
            "GulimChe" "DotumChe"
            "monospace")
       (symbol "Symbols Nerd Font Mono"
               "Noto Sans Symbols" "Noto Sans Symbols 2"
               "Segoe UI Symbol")
       (emoji "Noto Color Emoji"
              "Segoe UI Emoji")))
    (rangho-fonts-variable-font-alist
     '((nil "Noto Sans" "Noto Serif"
            "Segoe UI" "Arial"
            "sans-serif")
       (hangul "Noto Sans CJK KR" "Noto Serif CJK KR"
               "Malgun Gothic" "Dotum" "Gulim"
               "sans-serif")
       (kana "Noto Sans CJK JP" "Noto Serif CJK JP"
             "Meiryo" "Yu Gothic" "Yu Mincho"
             "sans-serif")
       (han ("Noto Sans CJK SC" "Noto Serif CJK SC")
            ("Noto Sans CJK TC" "Noto Serif CJK TC")
            "Microsoft YaHei" "Microsoft JhengHei"
            "sans-serif")
       (symbol "Symbols Nerd Font"
               "Noto Sans Symbols" "Noto Sans Symbols 2"
               "Segoe UI Symbol")
       (emoji "Noto Color Emoji"
              "Segoe UI Emoji")))
    :config
    (rangho-fonts-mode +1))
#+end_src

** Mode Line
Mode line indicates what file I'm editing, which mode I am using, etc.
However, the default mode line isn't really fun.
Let's customize that.

#+begin_src emacs-lisp
  (use-package rangho-modeline
    :ensure nil
    :custom
    (rangho-modeline-lhs-components
     (list
      #'rangho-modeline-buffer-status-component
      #'rangho-modeline-scroll-bar-component
      #'rangho-modeline-buffer-description-component))
    (rangho-modeline-rhs-components
     (list
      #'rangho-modeline-position-component
      #'rangho-modeline-evil-state-component))
    :config
    (rangho-modeline-mode +1))
#+end_src

** Theme
I have a custom theme that is based on the Material Design 3 color roles.
On desktop, ~noctalia~ will generate the theme and on laptop, ~pywal16~ will generate the theme.

#+begin_src emacs-lisp
  (cond
   ((member 'noctalia (custom-available-themes))
    ;; If there is a theme named `noctalia', load that theme.
    (load-theme 'noctalia t))
   ((executable-find "wal")
    ;; Since pywal-theme.el is always present, load the theme if "wal" binary is
    ;; available on the system.
    (load-theme 'pywal t))
   (t
    ;; Since no colorscheme generator is found, load the default material theme.
    (load-theme 'material t)))
#+end_src

* Keybindings
While emacs has an extensive list of keybindings available, we can make things much better and enjoyable.

** =ZERO WIDTH SPACE= Shortcut
While Org-mode is great, it doesn't handle markups beginning or ending within a word.
In English, this is rare, but in Korean and Japanese, it is a pain in the ass.
There should be an easy way to insert a *zero-width space* to delimit them.
(It is the [[https://orgmode.org/manual/Escape-Character.html][preferred way of achieving this]].)

#+begin_src emacs-lisp
  (with-eval-after-load 'evil
   (evil-define-key 'insert global-map (kbd "M-SPC")
    (lambda ()
      (interactive)
      (insert (char-from-name "ZERO WIDTH SPACE")))))
#+end_src

* Per-language Settings
These settings are for individual languages.
Some are programming languages, some are markups, and some are configuration languages.

Before loading individual configurations, ensure that all packages defined above are installed and loaded correctly.

Languages are organized in alphabetical orders, unless the package load order is significant.
(They should not be, though.)

** Agda
[[https://wiki.portal.chalmers.se/agda/pmwiki.php][Agda]] is a totally functional proof assistant and programming language.
Its documentation was pretty horrible back in the day, but it has got /a lot/ better recently.

#+begin_src emacs-lisp
  (use-package agda2
    :when (executable-find "agda")
    :load-path (lambda ()
                 (let ((coding-system-for-read 'utf-8))
                   (directory-file-name
                    (file-name-directory
                     (shell-command-to-string "agda --emacs-mode locate"))))))
#+end_src

** BASIC
While BASIC is not used a lot, some exotic environments like Microsoft Excel still requires a variant of it.

There is no official support for Visual Basic in =basic-mode=, so we need to define our own.

#+begin_src emacs-lisp
  (use-package basic-mode)

  (use-package visual-basic-mode
    :ensure nil)
#+end_src

** C, C++, Objective-C
These languages are supported via Emacs's built-in ~cc-mode~.

There are a lot of file extensions that Emacs doesn't recognize out-of-the-box, so we need to add them manually.
Also, while we're at it, let's enable Language Server support.

#+begin_src emacs-lisp
  (use-package c-ts-mode
    :mode (("\\.c\\'" . c-ts-mode)
           ("\\.h\\'" . c-or-c++-ts-mode)
           ("\\.HC\\'" . c-ts-mode)
           ("\\.ZC\\'" . c-ts-mode)
           ("\\.cpp\\'" . c++-ts-mode)
           ("\\.cppm\\'" . c++-ts-mode)
           ("\\.hpp\\'" . c++-ts-mode)
           ("\\.tpp\\'" . c++-ts-mode)
           ("\\.ipp\\'" . c++-ts-mode)
           ("\\.cc\\'" . c++-ts-mode)
           ("\\.hh\\'" . c++-ts-mode)
           ("\\.tcc\\'" . c++-ts-mode)
           ("\\.h++\\'" . c++-ts-mode)
           ("\\.c++\\'" . c++-ts-mode)
           ("\\.hxx\\'" . c++-ts-mode)
           ("\\.txx\\'" . c++-ts-mode)
           ("\\.cxx\\'" . c++-ts-mode)
           ("\\.inl\\'" . c++-ts-mode)
           ("\\.ixx\\'" . c++-ts-mode))
    :init
    (add-to-list 'treesit-language-source-alist
                 '(c "https://github.com/tree-sitter/tree-sitter-c"))
    (add-to-list 'treesit-language-source-alist
                 '(cpp "https://github.com/tree-sitter/tree-sitter-cpp"))
    :config
    (add-to-list 'major-mode-remap-alist
                 '(c-mode . c-ts-mode))
    (add-to-list 'major-mode-remap-alist
                 '(c++-mode . c++-ts-mode))
    (add-to-list 'major-mode-remap-alist
                 '(c-or-c++-mode . c-or-c++-ts-mode)))
#+end_src

Emacs doesn't come with support for build systems, except for Makefile.

#+begin_src emacs-lisp
  (use-package cmake-ts-mode
    :mode ("CMakeLists.txt\\'")
    :init
    (add-to-list 'treesit-language-source-alist
                 '(cmake "https://github.com/uyha/tree-sitter-cmake")))

  (use-package meson-mode
    :mode ("meson\\(\\.build\\|_options\\.txt\\|\\.options\\)\\'"))
#+end_src

We can add support for =clang-format= formatter with a bit of RegExp magic.

#+begin_src emacs-lisp
  (defun rangho--get-clang-format-item (config-string key &optional default)
    "Extract the value of KEY from `.clang-format' file's content provided as CONFIG-STRING."
    (let ((match-result (s-match (concat "^" key ":[ \t]*\\([a-zA-Z0-9]+\\)") config-string)))
      (if match-result
          (cadr match-result)
        default)))
#+end_src

** C#
Emacs C# with Roslyn literally trashes VS Code.

#+begin_src emacs-lisp
  (use-package csharp-mode
    :mode ("\\.cs\\'")
    :init
    (add-to-list 'treesit-language-source-alist
                 '(csharp "https://github.com/tree-sitter/tree-sitter-c-sharp"))
    :config
    (add-to-list 'major-mode-remap-alist
                 '(csharp-mode . csharp-ts-mode)))
#+end_src

** Caddyfile
Caddy is a simple and easy to use reverse proxy application.
Perfect solution for small web servers like in a homelab.

#+begin_src emacs-lisp
  (use-package caddyfile-mode
    :defer t)
#+end_src

** Conf-mode
~conf-mode~ provides support for INI-like files, such as UNIX =*.conf= files or Java =*.properties= files.

#+begin_src emacs-lisp
  (use-package conf-mode
    :mode ( ; systemd units
           "\\.service\\'" "\\.socket\\'" "\\.device\\'" "\\.mount\\'"
           "\\.automount\\'" "\\.swap\\'" "\\.target\\'" "\\.path\\'"
           "\\.timer\\'" "\\.slice\\'" "\\.scope\\'"
           ;; podman quadlets
           "\\.container\\'" "\\.network\\'" "\\.volume\\'" "\\.pod\\'"
           "\\.kube\\'" "\\.build\\'"))
#+end_src

** Crystal
Crystal is a native programming language that looks exactly like Ruby.

#+begin_src emacs-lisp
  (use-package crystal-mode
    :mode ("\\.cr\\'")
    :init
    (add-to-list 'eglot-server-programs
                 '(crystal-mode . ("crystalline"))))
#+end_src

** D2
D2 is a diagram scripting language, producing an image.

#+begin_src emacs-lisp
  (use-package d2-mode
    :defer t)
#+end_src

** Dockerfile
Docker is /de facto/ standard container technology these days.

#+begin_src emacs-lisp
  (use-package dockerfile-ts-mode
    :init
    (add-to-list 'treesit-language-source-alist
                 '(dockerfile "https://github.com/camdencheek/tree-sitter-dockerfile")))
#+end_src

** Elixir
Elixir is a functional programming langauge based on the great Erlang/OTP BEAM virtual machine.
It keeps the great part of the virtual machine while providing highly extensible grammar.

#+begin_src emacs-lisp
  (use-package elixir-ts-mode
    :init
    (add-to-list 'eglot-server-programs
                 '(elixir-mode . ("elixir-ls")))
    (add-to-list 'treesit-language-source-alist
                 '(elixir "https://github.com/elixir-lang/tree-sitter-elixir")))
#+end_src

HEEx is a template language used by Phoenix Framework, a popular web framework written in Elixir.

#+begin_src emacs-lisp
  (use-package heex-ts-mode
    :init
    (add-to-list 'treesit-language-source-alist
                 '(heex "https://github.com/phoenixframework/tree-sitter-heex")))
#+end_src

** F#
F# is a functional programming language in OCaml family that runs on .NET Common Language Runtime.

#+begin_src emacs-lisp
  (use-package fsharp-mode)

  (use-package eglot-fsharp
    :when (featurep 'eglot))
#+end_src

** Gnuplot
Gnuplot is a command-line plotting program.

#+begin_src emacs-lisp
  (use-package gnuplot)
#+end_src

** Go
Do I /really/ have to use Go?
Ugh...
At least it's built-in...

#+begin_src emacs-lisp
  (use-package go-ts-mode
    :mode (("\\.go\\'" . go-ts-mode)
           ("/go\\.mod\\'" . go-mod-ts-mode))
    :init
    (add-to-list 'treesit-language-source-alist
                 '(go "https://github.com/tree-sitter/tree-sitter-go"))
    (add-to-list 'treesit-language-source-alist
                 '(gomod "https://github.com/camdencheek/tree-sitter-go-mod")))
#+end_src

** Haskell
Haskell, being a purely functional language, has an exceptional support for Emacs.
So much so that it doesn't even require LSP!

#+begin_src emacs-lisp
  (use-package haskell-mode)
#+end_src

[[https://github.com/fourmolu/fourmolu][Fourmolu]] is a fork of [[https://github.com/tweag/ormolu][Ormolu]] with configurable style.
It is opinionated, but can make it into /my style/.
If =fourmolu= binary is available, integrate it.

#+begin_src emacs-lisp
  (use-package ormolu
    :when (executable-find "fourmolu")
    :hook (haskell-mode . ormolu-format-on-save-mode)
    :custom
    (ormolu-process-path "fourmolu"))
#+end_src

** Julia
[[https://julialang.org/][Julia]] is a scientific programming language that aims to replace R and Python.
Both of them suck, and Julia performs pretty well.

#+begin_src emacs-lisp
  (defconst rangho--julia-language-server-project
    (no-littering-expand-var-file-name "eglot/servers/julia"))

  (defconst rangho--julia-language-server-script
    (expand-file-name
     (locate-user-emacs-file (file-name-concat "usr" "bin" "eglot-julia"))))

  (defun rangho--julia-mode-contact (interactive project)
    "Produce the Eglot contact information for Julia language server for PROJECT.
  If INTERACTIVE is non-nil, then the request was made interactively; in that
  case, try installing the language server as well."
    ;; Assume that the existence of the project directory means that the language server is installed.
    (when interactive
      (rangho=julia-mode-install-server))
    (if (file-exists-p rangho--julia-language-server-project)
        (let (project-directory)
          (cond
           ((stringp project)
            (setq project-directory project))
           ((consp project)
            (setq project-directory (project-root project))))
          (list (executable-find "julia")
                "--startup-file=no"
                (concat "--project=" rangho--julia-language-server-project)
                rangho--julia-language-server-script
                "serve"
                project-directory))
      (user-error "Julia language server is not installed.  Please run `rangho-julia-mode-install-server' to install it")))

  (defun rangho-julia-mode-install-server ()
    "Install the Julia language server for Eglot."
    (interactive)
    ;; Make sure that the Julia project directory is available.
    (unless (file-exists-p rangho--julia-language-server-project)
      (make-directory rangho--julia-language-server-project t))
    (if (executable-find "julia")
        (make-comint-in-buffer "Julia LSP Install" "*Julia LSP Install*" "julia" nil
                            "--startup-file=no"
                            (concat "--project=" rangho--julia-language-server-project)
                            rangho--julia-language-server-script
                            "install")
      (user-error "Julia is not installed")))

  (use-package julia-mode
    :init
    (add-to-list 'eglot-server-programs
                 '(julia-mode . rangho--julia-mode-contact)))
#+end_src

** KDL
KDL is a small, pleasant document language with XML-like node semantics that resembles CLI commands.

#+begin_src emacs-lisp
  (use-package kdl-mode
    :init
    (add-to-list 'treesit-language-source-alist
                 '(kdl "https://github.com/tree-sitter-grammars/tree-sitter-kdl")))
#+end_src

** Lex and Yacc
Lex and Yacc (or more recently, Flex and Bison) are one of the most popular parser generator.

#+begin_src emacs-lisp
  (use-package bison-mode)
#+end_src

** Lua
Lua is a small, yet full-featured embedded language that works with C really well.

#+begin_src emacs-lisp
  (use-package lua-ts-mode
    :init
    (add-to-list 'treesit-language-source-alist
                 '(lua "https://github.com/tree-sitter-grammars/tree-sitter-lua")))
#+end_src

** Markdown
Markdown is a /de facto/ standard for writing README files on modern software projects.
The syntax is... questionable, at best, though.

#+begin_src emacs-lisp
  (use-package markdown-ts-mode
    :mode ("\\.md\\'" "\\.markdown\\'" "\\.mdx\\'")
    :init
    (add-to-list 'treesit-language-source-alist
                 '(markdown "https://github.com/tree-sitter-grammars/tree-sitter-markdown")))
#+end_src

** Mermaid
Mermaid is a diagram and graph scripting language, producing an image.

#+begin_src emacs-lisp
  (use-package mermaid-mode)
#+end_src

** Nix
Nix is a functional and declarative expression format used to configure NixOS.

#+begin_src emacs-lisp
  (use-package nix-ts-mode
    :mode ("\\.nix\\'")
    :init
    (add-to-list 'treesit-language-source-alist
                 '(nix "https://github.com/nix-community/tree-sitter-nix")))
#+end_src

** Nu
Nu is a brand-new, data-oriented shell script.

#+begin_src emacs-lisp
  (use-package nushell-ts-mode
    :mode ("\\.nu\\'")
    :init
    (add-to-list 'treesit-language-source-alist
                 '(nu "https://github.com/nushell/tree-sitter-nu")))
#+end_src

** OCaml
OCaml is an object-oriented extension of the Caml dialect of ML, mainly used in static analysis and formal verification softwares.

#+begin_src emacs-lisp
  (use-package tuareg)
#+end_src

** OpenSCAD
OpenSCAD allows me to make 3D models in code.

#+begin_src emacs-lisp
  (use-package scad-mode)
#+end_src

** Org-mode
~org-mode~ is a built-in package in Emacs, and is the best markup language.

#+begin_src emacs-lisp
  (use-package org
    :bind (("C-c a" . org-agenda)
           ("C-c t" . org-capture))
    :custom
    (org-auto-align-tags nil)
    (org-catch-invisible-edits 'show-and-error)
    (org-directory (file-truename
                    (expand-file-name "Documents/Notes" user-home-directory)))
    (org-default-notes-file (concat org-directory "/default.org"))
    (org-ellipsis "...")
    (org-hide-emphasis-markers t)
    (org-id-link-to-org-use-id t)
    (org-insert-heading-respect-content t)
    (org-pretty-entities t)
    (org-special-ctrl-a/e t)
    (org-startup-indented t)
    (org-startup-with-inline-images t)
    (org-tags-column 0)
    (org-use-sub-superscripts '{}))

  (use-package org-appear
    :hook (org-mode . (lambda ()
                        (org-appear-mode +1)
                        (add-hook 'evil-insert-state-entry-hook #'org-appear-manual-start nil t)
                        (add-hook 'evil-insert-state-exit-hook #'org-appear-manual-stop nil t)))
    :custom
    (org-appear-autoemphasis t)
    (org-appear-autoentities t)
    (org-appear-autolinks t)
    (org-appear-autosubmarkers t)
    (org-appear-inside-latex t)
    (org-appear-trigger 'manual))

  (use-package org-modern
    :after (nerd-icons)
    :hook ((org-mode . org-modern-mode)
           (org-agenda-finalize . org-modern-agenda))
    :custom
    (org-modern-star 'fold)
    (org-modern-fold-stars `((,(nerd-icons-mdicon "nf-md-chevron_right") . ,(nerd-icons-mdicon "nf-md-chevron_down"))
                             (,(nerd-icons-mdicon "nf-md-chevron_double_right") . ,(nerd-icons-mdicon "nf-md-chevron_double_down"))
                             (,(nerd-icons-mdicon "nf-md-chevron_triple_right") . ,(nerd-icons-mdicon "nf-md-chevron_triple_down"))
                             (,(nerd-icons-mdicon "nf-md-chevron_right_circle") . ,(nerd-icons-mdicon "nf-md-chevron_down_circle"))
                             (,(nerd-icons-mdicon "nf-md-chevron_right_circle_outline") . ,(nerd-icons-mdicon "nf-md-chevron_down_circle_outline")))))
#+end_src

~org-node~ brings the Zettelkasten method of notetaking into Emacs.

#+begin_src emacs-lisp
  (use-package org-mem
    :custom
    (org-mem-do-sync-with-org-id t)
    :config
    (org-mem-updater-mode))

  (use-package org-node
    :bind-keymap ("C-c n" . org-node-global-prefix-map)
    :config
    (org-node-cache-mode))
#+end_src

~org-re-reveal~ allows me to export an Org document into a Reveal.js presentation file.

#+begin_src emacs-lisp
  (use-package org-re-reveal
    :custom
    (org-re-reveal-root "https://cdn.jsdelivr.net/npm/reveal.js@4")
    (org-re-reveal-revealjs-version "4"))

  (use-package org-re-reveal-citeproc
    :config
    (add-to-list 'org-export-filter-paragraph-functions #'org-re-reveal-citeproc-filter-cite))
#+end_src

~ob-d2~ uses Mermaid to display graphs in Org documents.

#+begin_src emacs-lisp
  (use-package ob-d2
    :when (executable-find "d2")
    :init
    (add-to-list 'org-babel-load-languages '(d2 . t)))
#+end_src

~ob-gnuplot~ is built-in with Org mode distribution, and creates graphs in Org documents.

#+begin_src emacs-lisp
  (use-package ob-gnuplot
    :ensure nil
    :when (executable-find "gnuplot")
    :init
    (add-to-list 'org-babel-load-languages '(gnuplot . t)))
#+end_src

~ob-mermaid~ uses Mermaid to display graphs in Org documents.

#+begin_src emacs-lisp
  (use-package ob-mermaid
    :when (executable-find "mmdc")
    :custom
    (ob-mermaid-cli-path (executable-find "mmdc"))
    :init
    (add-to-list 'org-babel-load-languages '(mermaid . t)))
#+end_src

~ox-latex~ is a built-in package, but I need to use LuaLaTex if I want to do anything remotely related to CJK characters.

#+begin_src emacs-lisp
  (use-package ox-latex
    :ensure nil
    :custom
    (org-latex-compiler "lualatex")
    (org-latex-src-block-backend 'engraved)
    :init
    (add-to-list 'org-latex-packages-alist '("" "fvextra")))
#+end_src

** PowerShell
PowerShell is the new shell script language for Windows and .NET platform.

#+begin_src emacs-lisp
  (use-package powershell)
#+end_src

** Praat Script
Praat is a phonetics analysis software used by linguists.
It allows automation by writing object-manipulating commands into a script.

#+begin_src emacs-lisp
  (use-package praat-mode
    :ensure nil)
#+end_src

** Proof General
[[https://proofgeneral.github.io/][Proof General]] is a general Emacs interface for various proof assistants, and ships with major modes for Coq, EasyCrypt, qRHL, and PhoX.

#+begin_src emacs-lisp
  (use-package proof-general
    :custom
    (proof-splash-enable nil)
    (proof-layout-windows 'hybrid))
#+end_src

** Python
Python is overrated.
Still I need to use it, so...

#+begin_src emacs-lisp
  (use-package python
    :init
    (when (featurep 'treesit)
      (add-to-list 'treesit-language-source-alist
                   '(python "https://github.com/tree-sitter/tree-sitter-python")))
    :config
    (when (featurep 'treesit)
      (add-to-list 'major-mode-remap-alist
                   '(python-mode . python-ts-mode))))
#+end_src

** Ruby
Ruby is the father of system scripting language.
Better than Python.

#+begin_src emacs-lisp
  (use-package ruby-ts-mode
    :init
    (add-to-list 'treesit-language-source-alist
                 '(ruby "https://github.com/tree-sitter/tree-sitter-ruby")))

  (use-package rbs-mode)
#+end_src

** Rust
Rust is a modern system programming language that ensures memory safety by language design.

#+begin_src emacs-lisp
  (defun rangho--add-rust-mode-before-save-hook ()
    "Add a hook to format Rust code before saving."
    (add-hook 'before-save-hook #'eglot-format-buffer nil t))

  (use-package rust-ts-mode
    :hook (rust-ts-mode . rangho--add-rust-mode-before-save-hook)
    :init
    (add-to-list 'treesit-language-source-alist
                 '(rust "https://github.com/tree-sitter/tree-sitter-rust")))
#+end_src

** Swift
Swift is to Objective-C as Kotlin is to Java, on Apple devices.

#+begin_src emacs-lisp
  (use-package swift-mode)
#+end_src

** Terraform
Terraform is a cloud provisioning software from Hashicorp.

#+begin_src emacs-lisp
  (defun rangho--terraform-mode-contact (interactive)
    "Produce the Eglot contact information for Terraform language server.
  Ensure that Terraform language server is installed when called with INTERACTIVE."
    (let ((lsp-server (or (executable-find "terraform-ls")
                          (executable-find "tofu-ls"))))
      (when interactive
        (unless lsp-server
          (user-error "Neither terraform-ls nor tofu-ls is installed")))
      (list lsp-server "serve")))

  (use-package terraform-mode
    :init
    (add-to-list 'eglot-server-programs
                 '(terraform-mode . rangho--terraform-mode-contact)))
#+end_src

** TeX
TeX is a great typesetting engine.
It is also complicated as fuck.

We need to properly build ~auctex~ before actually loading it.
On non-UNIX systems this becomes a problem, but I won't be editing LaTeX on Windows anytime soon, so...

#+begin_src emacs-lisp
  (use-package auctex
    :hook ((ConTeXt-mode . prettify-symbols-mode)
           (LaTeX-mode . prettify-symbols-mode)))
#+end_src

** TOML
TOML, short for Tom's Obvious Minimal Language, is a minimal configuration file that extends simple INI files.
Starting from Emacs 29, a dedicated TOML mode powered by Tree-Sitter is built-in.

#+begin_src emacs-lisp
  (use-package toml-ts-mode
    :init
    (add-to-list 'treesit-language-source-alist
                 '(toml "https://github.com/tree-sitter/tree-sitter-toml"))
    :config
    (add-to-list 'major-mode-remap-alist
                 '(conf-toml-mode . toml-ts-mode)))
#+end_src

** Typst
Typst is a next-generation typesetting system with a markup language significantly easier than TeX.

Note that the major mode for Typst is provided only as a Tree-Sitter grammar.

#+begin_src emacs-lisp
  (use-package typst-ts-mode
    :init
    (add-to-list 'treesit-language-source-alist
                 '(typst "https://github.com/uben0/tree-sitter-typst")))
#+end_src

** Web Development
Web development, especially frontend development, is a pile of mess.
Emacs can help me with that.

*** CSS
Emacs has a good CSS support built-in.
There are a few /modern/ extensions to support, namely, PostCSS.

#+begin_src emacs-lisp
  (use-package css-mode
    :mode ("\\.pcss\\'" "\\.postcss\\'")
    :init
    (add-to-list 'treesit-language-source-alist
                 '(css "https://github.com/tree-sitter/tree-sitter-css"))
    :config
    (add-to-list 'major-mode-remap-alist
                 '(css-mode . css-ts-mode)))
#+end_src

*** JavaScript and JSX
JavaScript is such a pain in the ass to set up, as there are so many different "supersets".

There are three different ways to edit JavaScript in Emacs:

1. via ~js-mode~, a built-in JavaScript mode;
2. via ~js2-mode~, a major mode deriving from ~js-mode~ and provides AST parsing and linting.

TypeScript is ever-so-slightly better, but not by much.
Note that ~typescript.el~ is no longer supported as ~typescript-ts-mode~ is now built-in since Emacs 29.
To edit TypeScript files, just install Emacs 29.

#+begin_src emacs-lisp
  (use-package js
    :mode (("\\.js\\'" . js-ts-mode)
           ("\\.cjs\\'" . js-ts-mode)
           ("\\.mjs\\'" . js-ts-mode))
    :init
    (add-to-list 'treesit-language-source-alist
                 '(javascript "https://github.com/tree-sitter/tree-sitter-javascript"))
    :config
    (add-to-list 'major-mode-remap-alist
                 '(js-mode . js-ts-mode)))


#+end_src

*** TypeScript and TSX
React uses JavaScript with inline HTML-like markup syntax embedded within to declare components.
There is also a TypeScript variant of it, of course.

Until Emacs 28, the ~js~ package declared above handled JSX syntax, but starting from Emacs 29, there is a new major mode using Tree-Sitter.
While it says TSX, it supports both JSX and TSX no problem.

#+begin_src emacs-lisp
  (use-package typescript-ts-mode
    :mode (("\\.ts\\'" . typescript-ts-mode)
           ("\\.cts\\'" . typescript-ts-mode)
           ("\\.mts\\'" . typescript-ts-mode)
           ("\\.jsx\\'" . tsx-ts-mode)
           ("\\.tsx\\'" . tsx-ts-mode))
    :init
    (add-to-list 'treesit-language-source-alist
                 '(typescript "https://github.com/tree-sitter/tree-sitter-typescript" "v0.20.3" "typescript/src"))
    (add-to-list 'treesit-language-source-alist
                 '(tsx "https://github.com/tree-sitter/tree-sitter-typescript" "v0.20.3" "tsx/src"))
    :config
    (add-to-list 'major-mode-remap-alist
                 '(js-jsx-mode . tsx-ts-mode)))
#+end_src

*** JSON
JSON, short for JavaScript Object Notation, is a /de facto/ standard serialization method for multi-platform communiations.

Starting from Emacs 29, there is a new JSON major mode powered by Tree-Sitter.

#+begin_src emacs-lisp
  (use-package json-ts-mode
    :init
    (add-to-list 'treesit-language-source-alist
                 '(json "https://github.com/tree-sitter/tree-sitter-json"))
    :config
    (add-to-list 'major-mode-remap-alist
                 '(js-json-mode . json-ts-mode)))
#+end_src

*** Web-mode
Web-mode integrates all web-related languages into a single package nicely.
It primarily targets HTML, but it also supports other HTMLx templates.

#+begin_src emacs-lisp
  (defconst rangho--web-mode-server-programs
    '(("php" . ("phpactor" "language-server"))
      ("svelte" . ("svelteserver" "--stdio")))
    "Alist of language servers for `web-mode'.")

  (defun rangho--web-mode-contact (_)
    "Return the language server program for the current buffer."
    (if-let ((contact (assoc web-mode-engine rangho--web-mode-server-programs)))
        (cdr contact)
      '("echo" "No language server available")))

  (use-package web-mode
    :mode ("\\.php\\'"                      ; PHP
           "\\.rhtml\\'" "\\.html\\.erb\\'" ; Ruby on Rails
           "\\.html\\.heex\\'"              ; Phoenix
           "\\.ejs\\'"                      ; EJS
           "\\.svelte\\'"                   ; Svelte
           "\\.vue\\'"                      ; Vue.js
           "\\.html\\'")                    ; plain HTML (ofc)
    :custom
    (web-mode-enable-auto-quoting nil)
    :init
    (add-to-list 'eglot-server-programs
                 '(web-mode . rangho--web-mode-contact)))
#+end_src

** X Resource Database
X11 uses similar syntax for most of its configurations.

#+begin_src emacs-lisp
  (use-package xrdb-mode
    :ensure nil
    :mode ("\\.Xdefaults\\'" "\\.Xenvironment\\'" "\\.Xresources\\'"))
#+end_src

** YAML
[[https://yaml.org/][YAML]] is a human-readable data format with colon (=:=) as the separator and significant whitespaces.
While there are a lot of criticisms, it is still widely used to represent data in a human-readable format.

#+begin_src emacs-lisp
  (use-package yaml-mode
    :init
    (add-to-list 'treesit-language-source-alist
                 '(yaml "https://github.com/tree-sitter-grammars/tree-sitter-yaml")))
#+end_src
