#!/bin/sh

depends native fontconfig

if is arch platform; then
    depends native \
            noto-fonts \
            noto-fonts-cjk \
            noto-fonts-emoji \
            ttf-nerd-fonts-symbols
elif is void platform; then
    depends native \
            noto-fonts-ttf \
            noto-fonts-cjk \
            noto-fonts-emoji \
            nerd-fonts-symbols-ttf
fi