#!/bin/sh

#===============================================================================
#              _            _             _   
#   __ _ _   _| |_ ___  ___| |_ __ _ _ __| |_ 
#  / _` | | | | __/ _ \/ __| __/ _` | '__| __|
# | (_| | |_| | || (_) \__ \ || (_| | |  | |_ 
#  \__,_|\__,_|\__\___/|___/\__\__,_|_|   \__|
#
# Shell scripts to execute upon initialization of bspwm, created by RangHo.
#===============================================================================

## Ensure that the command/daemon is run only once
##
## Input
##     Command to ensure 
singleton() {
    local process_name="$1"
    local full_command="$@"

    killall -q "$process_name"

    # Wait until all instances of the process is shut down
    while pgrep -u "$UID" -x "$process_name" >/dev/null; do
        sleep 1
    done

    # Execute the command in the background
    eval "$full_command &"
}

# Run sxhkd for hotkeys
if [ "$(basename $SHELL)" == "fish" ]; then
    # sxhkd does not play nice with fish shell
    #export SXHKD_SHELL="/bin/sh"
    echo "doing nothing"
fi
SXHKD_SHELL="$(which sh)" singleton sxhkd

# Start uim daemon
singleton uim-xim

# Start picom compositor for prettier desktop.
singleton picom --experimental-backends --daemon

# Start MPRIS-Proxy to control bluetooth audio using MPRIS
singleton mpris-proxy

# Dunst must be started
singleton dunst

# Execute wmname becuase Java GUI is a fucktard
singleton wmname LG3D

# Load previously selected colorscmeme
wal -R

# Start Polybar
$HOME/.config/polybar/launch.sh

