#!/bin/sh

#===============================================================================
#              _            _             _   
#   __ _ _   _| |_ ___  ___| |_ __ _ _ __| |_ 
#  / _` | | | | __/ _ \/ __| __/ _` | '__| __|
# | (_| | |_| | || (_) \__ \ || (_| | |  | |_ 
#  \__,_|\__,_|\__\___/|___/\__\__,_|_|   \__|
#
# Shell scripts to execute upon initialization of bspwm, created by RangHo.
#===============================================================================

# Start compton compositor for prettier desktop.
compton --config ~/.config/compton/compton.conf --daemon &

# Start Polybar
$HOME/.config/polybar/launch.sh

# Set wallpaper image with feh.
feh --randomize --bg-fill ~/Pictures/Wallpapers/wallpaper-* &

# Start MPRIS-Proxy to control bluetooth audio using MPRIS
mpris-proxy &

# Dunst must be started
dunst &

# Execute wmname becuase Java GUI is a fucktard
wmname LG3D

