#!/bin/sh

#===============================================================================
#              _            _             _   
#   __ _ _   _| |_ ___  ___| |_ __ _ _ __| |_ 
#  / _` | | | | __/ _ \/ __| __/ _` | '__| __|
# | (_| | |_| | || (_) \__ \ || (_| | |  | |_ 
#  \__,_|\__,_|\__\___/|___/\__\__,_|_|   \__|
#
# Shell scripts to execute upon initialization of bspwm, created by RangHo.
#===============================================================================

## Ensure that the command/daemon is run only once
##
## Input
##     Command to ensure 
singleton() {
    local process_name="$1"
    local full_command="$@"

    killall -q "$1"

    # Wait until all instances of the process is shut down
    while pgrep -u "$UID" -x "$process_name" >/dev/null; do
        sleep 1
    done

    # Execute the command in the background
    eval "$@" &
}

# Start picom compositor for prettier desktop.
singleton picom --experimental-backends --daemon

# Set wallpaper image with feh.
singleton feh --randomize --bg-fill ~/Pictures/Wallpapers/wallpaper-*

# Start MPRIS-Proxy to control bluetooth audio using MPRIS
singleton mpris-proxy

# Dunst must be started
singleton dunst

# Execute wmname becuase Java GUI is a fucktard
singleton wmname LG3D

# Start Polybar
$HOME/.config/polybar/launch.sh
