#!/bin/sh

#===============================================================================
#  _                                 
# | |__  ___ _ ____      ___ __ ___  
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|                                  
# Created by RangHo.
#
# For a complete reference, run:
# man bspwm
#===============================================================================

# Set bspwm config directory
BSPWM_DIR=$HOME/.config/bspwm

# Define logoff command for Polybar
export LOGOFF_COMMAND="bspc quit"

# Make sure that .local/bin is in PATH
export PATH=$HOME/.local/bin:$PATH

# Set IME configs
export GTK_IM_MODULE=uim
export QT_IM_MODULE=uim
export XMODIFIERS=@im=uim

# Source colors from wal
source $HOME/.cache/wal/colors.sh

# Direct Qt to use GTK themes
export QT_QPA_PLATFORMTHEME=qt5ct

# Java GUI suffers with bspwm
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

# Create workspaces
bspc monitor -d web dev chat fun misc

# Use alternate insertion strategy
bspc config automatic_scheme alternate

# Set default border and gap
bspc config border_width            0
bspc config normal_border_color     $color1
bspc config focused_border_color    $color4
bspc config window_gap              50

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config presel_feedback_color $color10

# Enable mouse actions
bspc config pointer_modifier mod4
bspc config pointer_action1  move
bspc config pointer_action2  focus
bspc config pointer_action3  resize_corner

# Some application settings
bspc rule -a "Emacs" state=tiled
bspc rule -a "pavucontrol" state=floating

# Start programs in autostart list
$BSPWM_DIR/autostart

