;;; colors.el --- Color scheme definition automatically generated by pywal

;; Special colors
(defconst wal/foreground "#e0c8aa")
(defconst wal/background "#0f0f10")
(defconst wal/cursor "#e0c8aa")

;; Common colors
(defconst wal/color0 "#0f0f10")
(defconst wal/color1 "#59646C")
(defconst wal/color2 "#6F726F")
(defconst wal/color3 "#9E523E")
(defconst wal/color4 "#8D7661")
(defconst wal/color5 "#8F8879")
(defconst wal/color6 "#AE9573")
(defconst wal/color7 "#e0c8aa")
(defconst wal/color8 "#9c8c76")
(defconst wal/color9 "#59646C")
(defconst wal/color10 "#6F726F")
(defconst wal/color11 "#9E523E")
(defconst wal/color12 "#8D7661")
(defconst wal/color13 "#8F8879")
(defconst wal/color14 "#AE9573")
(defconst wal/color15 "#e0c8aa")

(provide 'pywal-colors)
