;;; colors.el --- Color scheme definition automatically generated by pywal

;; Special colors
(defconst foreground "#e0c8aa")
(defconst background "#0f0f10")
(defconst cursor "#e0c8aa")

;; Common colors
(defconst color0 "#0f0f10")
(defconst color1 "#59646C")
(defconst color2 "#6F726F")
(defconst color3 "#9E523E")
(defconst color4 "#8D7661")
(defconst color5 "#8F8879")
(defconst color6 "#AE9573")
(defconst color7 "#e0c8aa")
(defconst color8 "#9c8c76")
(defconst color9 "#59646C")
(defconst color10 "#6F726F")
(defconst color11 "#9E523E")
(defconst color12 "#8D7661")
(defconst color13 "#8F8879")
(defconst color14 "#AE9573")
(defconst color15 "#e0c8aa")

(provide 'pywal-colors)
