;;; colors.el --- Color scheme definition automatically generated by pywal

;; Special colors
(defconst wal/foreground "{foreground}")
(defconst wal/background "{background}")
(defconst wal/cursor "{cursor}")

;; Common colors
(defconst wal/color0 "{color0}")
(defconst wal/color1 "{color1}")
(defconst wal/color2 "{color2}")
(defconst wal/color3 "{color3}")
(defconst wal/color4 "{color4}")
(defconst wal/color5 "{color5}")
(defconst wal/color6 "{color6}")
(defconst wal/color7 "{color7}")
(defconst wal/color8 "{color8}")
(defconst wal/color9 "{color9}")
(defconst wal/color10 "{color10}")
(defconst wal/color11 "{color11}")
(defconst wal/color12 "{color12}")
(defconst wal/color13 "{color13}")
(defconst wal/color14 "{color14}")
(defconst wal/color15 "{color15}")

(provide 'pywal-colors)
