;;; colors-emacs.el --- Color scheme definition automatically generated by pywal

;; This file is generated by pywal.

;;; Commentary:

;; This file contains 16 ANSI terminal colors, as well as foreground, background
;; and cursor colors.  It itself does not apply any colors, but instead defines
;; constants that can be used in Emacs themes.

;;; Code:

;; Special colors
(defconst colors-emacs-foreground "{foreground}")
(defconst colors-emacs-background "{background}")
(defconst colors-emacs-cursor "{cursor}")

;; Common colors
(defconst colors-emacs-color0 "{color0}")
(defconst colors-emacs-color1 "{color1}")
(defconst colors-emacs-color2 "{color2}")
(defconst colors-emacs-color3 "{color3}")
(defconst colors-emacs-color4 "{color4}")
(defconst colors-emacs-color5 "{color5}")
(defconst colors-emacs-color6 "{color6}")
(defconst colors-emacs-color7 "{color7}")
(defconst colors-emacs-color8 "{color8}")
(defconst colors-emacs-color9 "{color9}")
(defconst colors-emacs-color10 "{color10}")
(defconst colors-emacs-color11 "{color11}")
(defconst colors-emacs-color12 "{color12}")
(defconst colors-emacs-color13 "{color13}")
(defconst colors-emacs-color14 "{color14}")
(defconst colors-emacs-color15 "{color15}")

(provide 'colors-emacs)
;;; colors-emacs.el ends here
