#!/bin/sh

depends native gtk2 gtk-engine-murrine qt5ct

if is arch platform; then
    depends native arc-gtk-theme \
                   papirus-icon-theme \
                   lxappearance
fi

pre_install() {
    is "~/.config/environment.d" directory?
    if no; then
        mkdir -p "~/.config/environment.d"
    fi

    rm -f ~/.config/gtk{-2.0,-3.0,-4.0,rc,rc-2.0}
}