;;; noctalia-theme.el --- Custom theme for Noctalia-generated color scheme. -*- lexical-binding: t -*-

;; Copyright (C) 2026 RangHo Lee

;;; Commentary:

;; A theme generated by Noctalia's template processor using the Material Design
;; 3 color roles produced from the active wallpaper or color scheme.

;;; Code:

(require 'rangho-themes)

(deftheme noctalia "Theme using noctalia-generated color scheme.")

(rangho-themes-define-theme
 'noctalia
 '((primary                  . "{{colors.primary.default.hex}}")
   (on-primary               . "{{colors.on_primary.default.hex}}")
   (primary-container        . "{{colors.primary_container.default.hex}}")
   (on-primary-container     . "{{colors.on_primary_container.default.hex}}")
   (secondary                . "{{colors.secondary.default.hex}}")
   (on-secondary             . "{{colors.on_secondary.default.hex}}")
   (secondary-container      . "{{colors.secondary_container.default.hex}}")
   (on-secondary-container   . "{{colors.on_secondary_container.default.hex}}")
   (tertiary                 . "{{colors.tertiary.default.hex}}")
   (on-tertiary              . "{{colors.on_tertiary.default.hex}}")
   (tertiary-container       . "{{colors.tertiary_container.default.hex}}")
   (on-tertiary-container    . "{{colors.on_tertiary_container.default.hex}}")
   (error                    . "{{colors.error.default.hex}}")
   (on-error                 . "{{colors.on_error.default.hex}}")
   (error-container          . "{{colors.error_container.default.hex}}")
   (on-error-container       . "{{colors.on_error_container.default.hex}}")
   (surface                  . "{{colors.surface.default.hex}}")
   (surface-container-lowest . "{{colors.surface_container_lowest.default.hex}}")
   (surface-container-low    . "{{colors.surface_container_low.default.hex}}")
   (surface-container        . "{{colors.surface_container.default.hex}}")
   (surface-container-high   . "{{colors.surface_container_high.default.hex}}")
   (surface-container-highest . "{{colors.surface_container_highest.default.hex}}")
   (on-surface               . "{{colors.on_surface.default.hex}}")
   (on-surface-variant       . "{{colors.on_surface_variant.default.hex}}")
   (outline                  . "{{colors.outline.default.hex}}")
   (outline-variant          . "{{colors.outline_variant.default.hex}}")
   (inverse-surface          . "{{colors.surface.default.hex}}")
   (inverse-on-surface       . "{{colors.on_surface.default.hex}}")
   (inverse-primary          . "{{colors.primary.default.hex}}")
   (scrim                    . "{{colors.shadow.default.hex}}")
   (shadow                   . "{{colors.shadow.default.hex}}")))

(provide-theme 'noctalia)

(provide 'noctalia-theme)
;;; noctalia-theme.el ends here
