(define byeoru-on-key '("<Shift> " "<Alt>Alt_key"))
(define byeoru-on-key? (make-key-predicate '("<Shift> " "<Alt>Alt_key")))
(define byeoru-latin-key '("<Shift> " "<Alt>Alt_key"))
(define byeoru-latin-key? (make-key-predicate '("<Shift> " "<Alt>Alt_key")))
(define byeoru-conversion-key '("F9" "<Control>Control_key"))
(define byeoru-conversion-key? (make-key-predicate '("F9" "<Control>Control_key")))
(define byeoru-commit-key '(generic-commit-key))
(define byeoru-commit-key? (make-key-predicate '(generic-commit-key?)))
(define byeoru-cancel-key '(generic-cancel-key))
(define byeoru-cancel-key? (make-key-predicate '(generic-cancel-key?)))
